#!/usr/bin/env python3
"""Defines semantic anchor table (id, category, hue, L, relC, harmony, en description, ru description).
Outputs ml/semantic_anchor_definitions.json. Human-curated; reproducible."""
import json, pathlib

A = 'analogous'; C = 'complementary'; S = 'splitComplementary'
# (id, category, hue, L, relC, harmony, en, ru)
rows = [
# --- neutrals ---
('black','color',0,0.10,0.05,A,'black color, absolute darkness, ink','черный цвет, абсолютная темнота, чернила'),
('white','color',95,0.95,0.04,A,'white color, pure light, snow white','белый цвет, чистый свет, белоснежный'),
('gray','color',230,0.52,0.06,A,'gray color, neutral tone','серый цвет, нейтральный тон'),
('silver','color',230,0.78,0.08,A,'silver color, metallic shine','серебряный цвет, металлический блеск'),
('charcoal','color',60,0.20,0.10,A,'charcoal, burnt wood black','древесный уголь, обугленное дерево'),
('ivory','color',90,0.90,0.10,A,'ivory, warm off-white','слоновая кость, теплый бело-кремовый'),
('cream','color',85,0.88,0.25,A,'cream, soft warm white','сливки, кремовый, мягкий теплый белый'),
('beige','color',80,0.80,0.30,A,'beige, sand neutral','бежевый, песочный нейтральный'),
# --- chromatic colors ---
('red','color',26,0.50,0.85,C,'red color, passion red','красный цвет, страстный красный'),
('crimson','color',22,0.45,0.85,C,'crimson, deep red','багровый, темно-красный'),
('scarlet','color',18,0.55,0.85,C,'scarlet, bright red','алый, ярко-красный'),
('orange','color',55,0.60,0.80,A,'orange color, vivid orange','оранжевый цвет, яркий оранжевый'),
('amber','color',70,0.60,0.80,A,'amber, warm golden orange','янтарный, тепло-золотистый'),
('yellow','color',95,0.75,0.85,A,'yellow color, sunny yellow','желтый цвет, солнечный желтый'),
('gold','color',85,0.70,0.80,A,'gold, golden metal, treasure','золото, золотой металл, сокровище'),
('lime','color',125,0.70,0.80,A,'lime, acid green','лаймовый, кислотно-зеленый'),
('green','color',145,0.45,0.70,A,'green color, pure green','зеленый цвет, чистый зеленый'),
('emerald','color',155,0.50,0.80,S,'emerald, precious green gem','изумруд, драгоценный зеленый камень'),
('olive','color',110,0.45,0.45,A,'olive, muted dark yellow-green','оливковый, приглушенный темно-зеленый'),
('mint','color',160,0.75,0.50,A,'mint, fresh pale green','мятный, свежий светло-зеленый'),
('teal','color',180,0.45,0.60,A,'teal, deep blue-green','морская волна, сине-зеленый'),
('cyan','color',195,0.60,0.75,S,'cyan color','циановый цвет'),
('turquoise','color',175,0.65,0.60,A,'turquoise, tropical water gem','бирюзовый, тропическая вода'),
('aqua','color',190,0.70,0.60,A,'aqua, clear light water','аква, прозрачная светлая вода'),
('blue','color',240,0.45,0.75,C,'blue color, pure blue','синий цвет, чистый синий'),
('skyblue','color',210,0.70,0.60,A,'sky blue, clear day sky','небесно-голубой, ясное небо'),
('navy','color',250,0.25,0.55,A,'navy, dark marine blue','темно-синий, морской темно-синий'),
('indigo','color',270,0.35,0.60,A,'indigo, deep violet-blue','индиго, глубокий сине-фиолетовый'),
('sapphire','color',245,0.45,0.70,S,'sapphire gem, royal blue','сапфир, королевский синий'),
('purple','color',295,0.45,0.75,S,'purple color, royal purple','фиолетовый цвет, королевский пурпур'),
('violet','color',290,0.50,0.75,S,'violet color','фиолетовый, синевато-лиловый'),
('lavender','color',300,0.75,0.40,A,'lavender, soft pale purple flower','лавандовый, мягкий бледно-лиловый'),
('lilac','color',300,0.70,0.45,A,'lilac flower, light purple','сиреневый, светло-фиолетовый'),
('magenta','color',330,0.50,0.85,S,'magenta, vivid purplish red','пурпурный, яркий фиолетово-красный'),
('pink','color',350,0.70,0.60,A,'pink color, soft pink','розовый цвет, мягкий розовый'),
('rose','color',355,0.60,0.60,A,'rose, romantic red-pink flower','роза, романтичный красно-розовый'),
('burgundy','color',15,0.30,0.60,A,'burgundy, dark wine red','бордовый, темный винный'),
('maroon','color',20,0.35,0.55,A,'maroon, brownish red','темно-бордовый, каштановый'),
('brown','color',55,0.40,0.50,A,'brown color, earth','коричневый цвет, земля'),
('chocolate','color',40,0.30,0.50,A,'chocolate, dark cocoa','шоколад, темное какао'),
('tan','color',65,0.60,0.40,A,'tan, sandy leather','цвет загара, кожаный песочный'),
('peach','color',35,0.75,0.45,A,'peach fruit, warm pale orange','персик, теплый бледно-оранжевый'),
('coral','color',25,0.65,0.60,A,'coral, warm sea orange-pink','коралловый, оранжево-розовый'),
('salmon','color',30,0.65,0.50,A,'salmon, soft orange pink','лососевый, мягкий оранжево-розовый'),
('rust','color',45,0.45,0.65,A,'rust, oxidized iron, corroded metal','ржавчина, окисленное железо'),
('copper','color',45,0.50,0.60,A,'copper metal','медь, медный металл'),
('bronze','color',55,0.45,0.55,A,'bronze, aged metal','бронза, старый металл'),
('blood','color',20,0.35,0.70,C,'blood, deep red liquid','кровь, густая красная жидкость'),
('plum','color',300,0.30,0.50,A,'plum fruit, dark purple','слива, темно-фиолетовый'),
# --- seasons / weather / time ---
('winter','season',225,0.30,0.35,S,'winter, cold snowy season','зима, холодный снежный сезон'),
('snow','weather',220,0.80,0.20,A,'snow, snowfall, white blanket','снег, снегопад, белое покрывало'),
('arctic','nature',210,0.75,0.30,A,'arctic, polar ice','арктика, полярный лед'),
('ice','nature',200,0.75,0.40,A,'ice, frozen transparent','лед, замерзшая прозрачность'),
('frost','weather',220,0.80,0.15,A,'frost, freezing crystals','иней, морозные кристаллы'),
('spring','season',120,0.70,0.50,A,'spring, fresh bloom','весна, свежее цветение'),
('summer','season',90,0.65,0.55,A,'summer, hot sunny season','лето, жаркий солнечный сезон'),
('autumn','season',55,0.50,0.60,A,'autumn, falling leaves season','осень, сезон падающих листьев'),
('rain','weather',230,0.45,0.30,A,'rain, rainy wet weather','дождь, дождливая погода'),
('storm','weather',240,0.30,0.35,S,'storm, heavy dark clouds','гроза, шторм, темные тучи'),
('fog','weather',220,0.70,0.12,A,'fog, misty haze','туман, дымка'),
('overcast','weather',230,0.60,0.10,A,'overcast grey sky','пасмурное серое небо'),
('tropical','nature',160,0.55,0.55,A,'tropical paradise, palm beach','тропики, пальмовый пляж'),
('night','time',250,0.15,0.30,A,'night, darkness after sunset','ночь, темнота после заката'),
('midnight','time',255,0.12,0.40,A,'midnight, deep night','полночь, глухая ночь'),
('moonlight','time',230,0.35,0.30,A,'moonlight, pale night glow','лунный свет, бледное ночное свечение'),
('starrysky','nature',260,0.20,0.45,S,'starry sky, stars in the night','звездное небо, звезды ночью'),
('dawn','time',45,0.65,0.50,A,'dawn, first light','рассвет, первый свет'),
('sunrise','time',50,0.60,0.60,A,'sunrise, morning sun','восход, утреннее солнце'),
('sunset','time',45,0.50,0.65,A,'sunset, evening glow','закат, вечернее зарево'),
('dusk','time',290,0.30,0.40,A,'dusk, twilight after sunset','сумерки после заката'),
('twilight','time',270,0.30,0.40,A,'twilight, dim evening light','сумерки, тусклый вечерний свет'),
# --- nature / places ---
('ocean','nature',220,0.40,0.50,C,'ocean, open sea water','океан, открытое море'),
('deepsea','nature',230,0.20,0.45,S,'deep sea, underwater abyss','глубины моря, подводная бездна'),
('sea','nature',200,0.45,0.50,A,'sea, seaside water','море, морская вода'),
('beach','place',75,0.70,0.40,A,'beach, sand and sun','пляж, песок и солнце'),
('desert','place',70,0.60,0.55,A,'desert, hot sand waste','пустыня, раскаленный песок'),
('savanna','nature',80,0.55,0.45,A,'savanna, dry grassland','саванна, сухая трава'),
('forest','nature',140,0.35,0.45,A,'forest, dense trees','лес, густые деревья'),
('pineforest','nature',150,0.28,0.40,A,'pine forest, dark coniferous woods','сосновый лес, темный хвойный бор'),
('jungle','nature',135,0.40,0.50,A,'jungle, tropical rainforest','джунгли, тропический лес'),
('meadow','nature',115,0.60,0.50,A,'meadow, flowering grass field','луг, цветущее поле'),
('volcano','nature',25,0.25,0.60,C,'volcano, eruption','вулкан, извержение'),
('lava','nature',25,0.35,0.75,C,'lava, molten rock','лава, расплавленная порода'),
('mountain','nature',230,0.45,0.30,A,'mountain, rocky peaks','горы, скалистые вершины'),
('canyon','nature',50,0.50,0.50,A,'canyon, red rock gorge','каньон, красная скалистая теснина'),
('cave','place',80,0.15,0.20,A,'cave, dark underground hollow','пещера, темная подземная полость'),
('swamp','nature',130,0.35,0.45,A,'swamp, murky wetland','болото, мрачная топь'),
('toxicswamp','nature',135,0.45,0.70,S,'toxic swamp, poisonous green ooze','токсичное болото, ядовитая жижа'),
('river','nature',210,0.50,0.45,A,'river flowing water','река, текущая вода'),
('lake','nature',200,0.45,0.40,A,'lake, still water','озеро, неподвижная вода'),
('moon','space',230,0.60,0.15,A,'the moon, lunar surface','луна, лунная поверхность'),
('mars','space',35,0.45,0.55,S,'mars, red desert planet','марс, красная пустынная планета'),
('space','space',265,0.15,0.50,S,'outer space, cosmos','космос, вселенная'),
('galaxy','space',280,0.20,0.55,S,'galaxy, spiral stars','галактика, спираль звезд'),
('nebula','space',300,0.30,0.60,S,'nebula, colorful cosmic cloud','туманность, космическое облако'),
('sun','space',75,0.70,0.75,A,'the sun, bright solar light','солнце, яркий солнечный свет'),
# --- urban / places ---
('citynight','urban',250,0.30,0.50,S,'city at night, street lights','город ночью, огни улиц'),
('neoncity','urban',310,0.40,0.80,S,'neon city, glowing signs','неоновый город, светящиеся вывески'),
('cyberpunk','style',305,0.40,0.85,S,'cyberpunk, neon future dystopia','киберпанк, неоновая антиутопия'),
('tokyonight','urban',300,0.35,0.70,S,'tokyo at night, neon streets','токио ночью, неоновые улицы'),
('hospital','place',180,0.70,0.25,A,'hospital, clean medical','больница, чистая медицина'),
('abandonedhospital','place',160,0.35,0.30,A,'abandoned hospital, creepy ruins','заброшенная больница, жуткие руины'),
('morgue','place',200,0.30,0.15,A,'morgue, cold sterile death','морг, холодная стерильность'),
('cemetery','place',150,0.30,0.20,A,'cemetery, graveyard','кладбище, могилы'),
('church','place',70,0.50,0.30,A,'church, sacred interior','церковь, священное убранство'),
('monastery','place',80,0.55,0.25,A,'monastery, quiet stone halls','монастырь, тихие каменные залы'),
('library','place',65,0.40,0.35,A,'library, old books','библиотека, старые книги'),
('school','place',65,0.55,0.30,A,'school, classroom','школа, класс'),
('office','place',220,0.65,0.20,A,'office, corporate workspace','офис, рабочее пространство'),
('factory','industrial',55,0.40,0.45,A,'factory, industrial plant','завод, промышленное предприятие'),
('rustyfactory','industrial',45,0.45,0.60,S,'rusty abandoned factory','ржавый заброшенный завод'),
('industrial','industrial',60,0.40,0.35,A,'industrial zone, machinery','промзона, механизмы'),
('warehouse','industrial',65,0.35,0.20,A,'warehouse, storage hall','склад, хранилище'),
('basement','place',70,0.20,0.20,A,'basement, damp underground room','подвал, сырая подземная комната'),
('bunker','place',220,0.30,0.20,A,'bunker, concrete shelter','бункер, бетонное убежище'),
('prison','place',80,0.30,0.20,A,'prison, jail cells','тюрьма, камеры'),
('subway','urban',250,0.30,0.35,A,'subway, underground metro','метро, подземка'),
('trainstation','urban',50,0.45,0.30,A,'train station, railway','вокзал, железная дорога'),
('hotel','place',40,0.45,0.40,A,'hotel lobby','отель, гостиничный холл'),
('motel','place',350,0.40,0.50,A,'cheap motel, roadside neon','дешевый мотель, придорожный неон'),
('casino','place',345,0.40,0.70,S,'casino, gambling lights','казино, азартные огни'),
('bar','place',30,0.30,0.50,A,'bar, dim drinking place','бар, полумрак'),
('cafe','place',60,0.55,0.45,A,'cafe, cozy coffee place','кафейня, уютное место'),
('restaurant','place',45,0.40,0.40,A,'restaurant, fine dining','ресторан, изысканная кухня'),
('bakery','place',65,0.65,0.45,A,'bakery, fresh bread','пекарня, свежий хлеб'),
('market','place',60,0.55,0.45,A,'market, bazaar stalls','рынок, торговые ряды'),
('deadmall','place',230,0.45,0.18,A,'dead shopping mall, empty stores','мертвый торговый центр, пустые магазины'),
('museum','place',60,0.50,0.25,A,'museum, gallery halls','музей, залы галереи'),
('theater','place',350,0.35,0.50,A,'theater, stage curtains','театр, сцена и занавес'),
('cinema','place',270,0.20,0.30,A,'cinema, dark movie hall','кинотеатр, темный зал'),
('arcade','tech',260,0.35,0.60,S,'arcade hall, game machines','игровой зал, автоматы'),
('computerclub','tech',250,0.30,0.60,S,'computer club, old PCs','компьютерный клуб, старые ПК'),
('laboratory','place',190,0.70,0.25,A,'laboratory, sterile science','лаборатория, стерильная наука'),
('serverroom','tech',230,0.35,0.45,A,'server room, racks of machines','серверная, стойки с машинами'),
# --- tech / retro / style ---
('retro','style',45,0.50,0.55,A,'retro, vintage seventies','ретро, винтаж'),
('synthwave','style',310,0.45,0.80,S,'synthwave, eighties retro electronic','синтвейв, восьмидесятые'),
('vaporwave','style',300,0.60,0.70,S,'vaporwave aesthetic','вайпорвейв эстетика'),
('vhs','tech',180,0.40,0.35,A,'old vhs tape, analog video noise','старая видеокассета, аналоговый шум'),
('crt','tech',180,0.50,0.45,A,'old crt monitor glow','старый ЭЛТ-монитор'),
('terminal','tech',140,0.35,0.55,A,'terminal, green on black text','терминал, зеленый текст на черном'),
('soviet','style',50,0.45,0.30,A,'soviet era, soviet style','советская эпоха, советский стиль'),
('brutalism','style',220,0.45,0.15,A,'brutalism, raw concrete','брутализм, грубый бетон'),
('concrete','material',220,0.50,0.12,A,'concrete, grey cement','бетон, серый цемент'),
('asphalt','material',230,0.25,0.10,A,'asphalt, road surface','асфальт, дорожное покрытие'),
('steel','material',230,0.55,0.15,A,'steel, cold metal','сталь, холодный металл'),
('wood','material',65,0.45,0.40,A,'wood, timber texture','дерево, текстура древесины'),
('leather','material',40,0.35,0.40,A,'leather, worn brown','кожа, потертая коричневая'),
('marble','material',230,0.75,0.12,A,'marble, polished stone','мрамор, полированный камень'),
('sand','material',75,0.70,0.40,A,'sand, warm desert grains','песок, теплые песчинки'),
# --- food ---
('coffee','food',50,0.35,0.45,A,'coffee, roasted beans','кофе, обжаренные зерна'),
('espresso','food',35,0.25,0.40,A,'espresso, strong dark coffee','эспрессо, крепкий темный кофе'),
('tea','food',70,0.55,0.40,A,'tea, warm cup','чай, теплая чашка'),
('matcha','food',120,0.60,0.50,A,'matcha, green tea powder','матча, зеленый чай'),
('wine','food',10,0.30,0.60,A,'wine, red wine glass','вино, бокал красного'),
('whiskey','food',55,0.45,0.60,A,'whisky, amber liquor','виски, янтарный напиток'),
('beer','food',80,0.60,0.60,A,'beer, golden ale','пиво, золотистый эль'),
('water','food',210,0.70,0.30,A,'pure water, clear drink','чистая вода, прозрачный напиток'),
('milk','food',90,0.90,0.08,A,'milk, white creamy','молоко, белое сливочное'),
('honey','food',75,0.60,0.70,A,'honey, golden sweet','мед, золотистая сладость'),
('candy','food',330,0.65,0.70,A,'candy, sweets','конфеты, сладости'),
('icecream','food',180,0.75,0.40,A,'ice cream, cold dessert','мороженое, холодный десерт'),
('strawberry','food',10,0.55,0.70,A,'strawberry, ripe red berry','клубника, спелая ягода'),
('lemon','food',95,0.75,0.80,A,'lemon, sour yellow citrus','лимон, кислый цитрус'),
('blueberry','food',260,0.35,0.50,A,'blueberry, dark blue berry','черника, темно-синяя ягода'),
('grape','food',300,0.35,0.55,A,'grapes, purple fruit','виноград, фиолетовый плод'),
('cherry','food',15,0.45,0.70,A,'cherry, ripe red fruit','вишня, спелый красный плод'),
('tomato','food',25,0.50,0.70,A,'tomato, red vegetable','помидор, красный овощ'),
('pumpkin','food',60,0.55,0.60,A,'pumpkin, orange gourd','тыква, оранжевая'),
('cinnamon','food',45,0.45,0.55,A,'cinnamon, warm spice','корица, теплая специя'),
('vanilla','food',80,0.80,0.25,A,'vanilla, soft sweet pale','ваниль, мягкий сладкий'),
# --- fantasy / horror ---
('alien','fantasy',140,0.50,0.60,S,'alien, extraterrestrial','пришелец, инопланетный'),
('dragon','fantasy',30,0.40,0.60,S,'dragon, fire scales','дракон, огненная чешуя'),
('fairy','fantasy',320,0.70,0.50,A,'fairy, tiny magic lights','фея, волшебные огоньки'),
('magic','fantasy',290,0.45,0.70,S,'magic, arcane spells','магия, тайные заклинания'),
('darkmagic','fantasy',280,0.25,0.60,S,'dark magic, forbidden sorcery','темная магия, запретное колдовство'),
('enchantedforest','fantasy',150,0.40,0.50,A,'enchanted forest, fairytale woods','волшебный лес, сказочная чаща'),
('unicorn','fantasy',330,0.75,0.55,A,'unicorn, pastel fantasy','единорог, пасторальная сказка'),
('mermaid','fantasy',180,0.50,0.55,A,'mermaid, sea maiden','русалка, морская дева'),
('ghost','horror',220,0.75,0.10,A,'ghost, pale apparition','призрак, бледное видение'),
('vampire','horror',15,0.20,0.50,A,'vampire, gothic blood','вампир, готическая кровь'),
('zombie','horror',110,0.40,0.45,A,'zombie, rotting undead','зомби, гниющие мертвецы'),
('witch','fantasy',270,0.25,0.50,A,'witch, dark sorceress','ведьма, темная колдунья'),
('pirate','fantasy',50,0.35,0.40,A,'pirate, sea rover','пират, морской разбойник'),
('royal','style',275,0.35,0.55,S,'royal, regal palace','королевский, дворцовый'),
('knight','fantasy',230,0.40,0.30,A,'knight, steel armor','рыцарь, стальная броня'),
# --- moods / abstract ---
('love','mood',350,0.55,0.60,A,'love, romantic feeling','любовь, романтическое чувство'),
('romance','mood',345,0.60,0.55,A,'romance, tender evening','романтика, нежный вечер'),
('toxiclove','mood',335,0.45,0.75,S,'toxic love, poisonous passion','токсичная любовь, ядовитая страсть'),
('passion','mood',20,0.50,0.75,C,'passion, burning desire','страсть, жгучее желание'),
('anger','mood',25,0.45,0.70,C,'anger, fury','злость, ярость'),
('calm','mood',210,0.60,0.30,A,'calm, peaceful stillness','покой, безмятежность'),
('loneliness','mood',235,0.30,0.30,A,'loneliness, empty solitude','одиночество, пустота'),
('sadness','mood',240,0.40,0.35,A,'sadness, sorrow','грусть, печаль'),
('melancholy','mood',250,0.40,0.30,A,'melancholy, wistful dusk','меланхолия, тоскливые сумерки'),
('nostalgia','mood',55,0.50,0.40,A,'nostalgia, warm old memories','ностальгия, теплые старые воспоминания'),
('dream','mood',280,0.50,0.50,A,'dream, soft sleep visions','сон, мягкие видения'),
('nightmare','mood',270,0.15,0.45,S,'nightmare, terrifying dream','кошмар, ужасный сон'),
('hope','mood',80,0.65,0.50,A,'hope, morning light','надежда, утренний свет'),
('joy','mood',60,0.70,0.60,A,'joy, bright happiness','радость, светлое счастье'),
('fear','mood',250,0.20,0.35,A,'fear, dread darkness','страх, темный ужас'),
('horror','mood',265,0.15,0.40,S,'horror, dread and darkness','хоррор, мрак и ужас'),
('danger','mood',15,0.45,0.65,C,'danger, alarm','опасность, тревога'),
('toxic','mood',130,0.50,0.70,S,'toxic, poisonous','токсичный, ядовитый'),
('radioactive','mood',120,0.60,0.80,S,'radioactive, glowing hazard','радиоактивный, светящаяся угроза'),
('death','mood',250,0.15,0.15,A,'death, mourning','смерть, траур'),
('luxury','mood',45,0.40,0.55,S,'luxury, rich expensive gold','роскошь, богатое золото'),
('elegance','mood',340,0.45,0.45,A,'elegant, refined style','элегантность, утонченность'),
('cozy','mood',60,0.55,0.45,A,'cozy, warm comfortable','уют, тепло и комфорт'),
('warmth','mood',55,0.55,0.55,A,'warm, warmness','тепло, теплота'),
('cold','mood',225,0.50,0.35,A,'cold, icy chill','холод, ледяной озноб'),
('fresh','mood',160,0.65,0.45,A,'fresh, crisp clean','свежесть, чистота'),
('freedom','mood',190,0.65,0.45,A,'freedom, open sky','свобода, открытое небо'),
('energy','mood',40,0.60,0.75,S,'energy, powerful drive','энергия, мощный заряд'),
('mystery','mood',275,0.25,0.50,A,'mystery, secret enigma','тайна, загадка'),
('space_dream','mood',290,0.35,0.60,S,'dream about space, cosmic dream','сон про космос'),
]

out = []
for r in rows:
    out.append({
        'id': r[0], 'category': r[1],
        'intent': {'hue': r[2], 'l': r[3], 'relC': r[4], 'harmony': r[5]},
        'en': r[6], 'ru': r[7],
    })
path = pathlib.Path(__file__).resolve().parent / 'semantic_anchor_definitions.json'
path.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding='utf-8')
print(f'{len(out)} anchors -> {path}')
