import { Palette, PaletteColor } from '@/types/palette';
import { getPaletteColorLabel } from '../colorNaming';

function getColors(palette: Palette): PaletteColor[] {
  if (!palette || (!palette.colors && !palette.base)) return [];

  return palette.colors && palette.colors.length > 0
    ? palette.colors
    : [palette.shadow, palette.base, palette.highlight, palette.accent].filter(Boolean);
}

function variableName(color: PaletteColor, index: number, count: number): string {
  const label = getPaletteColorLabel(color.role, index, count, color.oklch)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

  return `--palette-${index + 1}-${label || 'color'}`;
}

export function generateCssString(palette: Palette): string {
  const colors = getColors(palette);
  if (colors.length === 0) return ':root {}\n';

  const variables = colors.map((color, index) => ({
    name: variableName(color, index, colors.length),
    hex: (color.hex || '#000000').toUpperCase(),
    oklch: `oklch(${(color.oklch.l * 100).toFixed(2)}% ${color.oklch.c.toFixed(4)} ${color.oklch.h === null ? 'none' : color.oklch.h.toFixed(2)})`,
  }));

  const fallback = variables.map(({ name, hex }) => `  ${name}: ${hex};`).join('\n');
  const modern = variables.map(({ name, oklch }) => `    ${name}: ${oklch};`).join('\n');

  return `/* Generated by OKLCH Pixel Palette */\n:root {\n${fallback}\n}\n\n@supports (color: oklch(50% 0 0)) {\n  :root {\n${modern}\n  }\n}\n`;
}
