'use client';

import React, { useState, useCallback, useRef, useEffect, useImperativeHandle } from 'react';
import { Sparkles, Loader2, AlertCircle } from 'lucide-react';
import type { OklchColor } from '@/types/palette';

export interface AiApplyResult {
  colors: OklchColor[];
  seed: number;
  modelVersion: string;
  inference?: {
    encoderMs?: number;
    decoderMs?: number;
    totalMs?: number;
  };
  fallback?: boolean;
  prompt: string;
}

export interface AiLockedColor {
  index: number;
  oklch: OklchColor;
}

export interface AiPaletteInputHandle {
  generate: (options?: { seed?: number; count?: number }) => Promise<boolean>;
  focus: () => void;
}

interface AiPaletteInputProps {
  onApply: (result: AiApplyResult) => void;
  count: number;
  onCountChange: (count: number) => void;
  seed: number;
  lockedColors?: AiLockedColor[];
  locale?: 'en' | 'ru';
  className?: string;
  initialPrompt?: string;
}

type State = 'idle' | 'loading' | 'error';

const PLACEHOLDER_EN = 'winter starry forest';
const PLACEHOLDER_RU = 'зимний звездный лес';

const SUGGESTIONS_EN = [
  'winter starry forest',
  'purple cave',
  'deep sea horror',
  'pale pink sunrise',
  'cyberpunk neon',
  'cozy autumn cafe',
];

const SUGGESTIONS_RU = [
  'зимний звездный лес',
  'фиолетовая пещера',
  'ужас глубин океана',
  'бледно-розовый рассвет',
  'неоновый киберпанк',
  'уютная кофейня',
];

const COUNT_OPTIONS = [2, 3, 4, 5, 6, 7, 8, 9] as const;

interface RuntimeAiResult {
  colors: OklchColor[];
  seed: number;
  modelVersion: string;
  inference?: AiApplyResult['inference'];
  fallback?: boolean;
}

export const AiPaletteInput = React.forwardRef<AiPaletteInputHandle, AiPaletteInputProps>(function AiPaletteInput(
  {
    onApply,
    count,
    onCountChange,
    seed,
    lockedColors = [],
    locale = 'en',
    className = '',
    initialPrompt = '',
  },
  ref,
) {
  const isRu = locale === 'ru';
  const suggestions = isRu ? SUGGESTIONS_RU : SUGGESTIONS_EN;

  const [prompt, setPrompt] = useState(initialPrompt);
  const [state, setState] = useState<State>('idle');
  const [error, setError] = useState<string | null>(null);
  const [lastResult, setLastResult] = useState<Pick<RuntimeAiResult, 'modelVersion' | 'inference' | 'fallback'> | null>(null);
  const isGenerating = state === 'loading';
  const inputRef = useRef<HTMLInputElement>(null);
  const hasAutoGenerated = useRef(false);
  const inFlightRef = useRef(false);

  const runGeneration = useCallback(async (
    explicitPrompt?: string,
    options?: { seed?: number; count?: number; lockedColors?: AiLockedColor[] },
  ): Promise<boolean> => {
    const trimmed = (explicitPrompt ?? inputRef.current?.value ?? prompt).trim();
    if (!trimmed) {
      setError(isRu ? 'Опишите палитру перед генерацией.' : 'Describe a palette before generating.');
      setState('error');
      inputRef.current?.focus();
      return false;
    }
    if (inFlightRef.current) return false;

    const requestedCount = options?.count ?? count;
    if (!Number.isInteger(requestedCount) || requestedCount < 2 || requestedCount > 9) {
      setError(isRu ? 'Количество цветов должно быть от 2 до 9.' : 'Color count must be between 2 and 9.');
      setState('error');
      return false;
    }

    inFlightRef.current = true;
    setState('loading');
    setError(null);
    setLastResult(null);

    try {
      // Lazy load the local runtime only when AI mode is actually used.
      const { generateAiPalette } = await import('@/lib/ai-palette/inference');

      const result = await generateAiPalette({
        prompt: trimmed,
        count: requestedCount,
        seed: options?.seed ?? seed,
        lockedColors: (options?.lockedColors ?? lockedColors)
          .filter((locked) => locked.index >= 0 && locked.index < requestedCount)
          .map((locked) => ({ index: locked.index, oklch: { ...locked.oklch } })),
      });

      if (typeof window !== 'undefined') {
        (window as unknown as { __paletteBrainLastResult?: typeof result }).__paletteBrainLastResult = result;
      }

      if (!Array.isArray(result.colors) || result.colors.length !== requestedCount) {
        throw new Error(`AI returned ${result.colors?.length ?? 0} colors; expected ${requestedCount}.`);
      }
      if (!result.modelVersion || !Number.isFinite(result.seed)) {
        throw new Error('AI returned incomplete generation metadata.');
      }

      onApply({ ...result, prompt: trimmed });
      setLastResult({
        modelVersion: result.modelVersion,
        inference: result.inference,
        fallback: result.fallback,
      });
      setState('idle');
      return true;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error('[AI Palette]', err);
      setError(msg);
      setState('error');
      return false;
    } finally {
      inFlightRef.current = false;
    }
  }, [count, isRu, lockedColors, onApply, prompt, seed]);

  const handleGenerate = useCallback(() => {
    void runGeneration();
  }, [runGeneration]);

  useImperativeHandle(ref, () => ({
    generate: (options) => runGeneration(undefined, options),
    focus: () => inputRef.current?.focus(),
  }), [runGeneration]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter') {
        e.preventDefault();
        handleGenerate();
      }
    },
    [handleGenerate],
  );

  const handleRetry = useCallback(() => {
    void runGeneration();
  }, [runGeneration]);

  const handleChipClick = (suggestion: string) => {
    setPrompt(suggestion);
    if (inputRef.current) {
      inputRef.current.value = suggestion;
    }
  };

  // Auto-generate if initialPrompt was provided via URL/redirect
  useEffect(() => {
    if (initialPrompt && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      setPrompt(initialPrompt);
      if (inputRef.current) {
        inputRef.current.value = initialPrompt;
      }
      void runGeneration(initialPrompt);
    }
  }, [initialPrompt, runGeneration]);

  // Test and programmatic hook
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const testWindow = window as unknown as {
        __generateAiPalette?: (text: string, options?: { seed?: number; count?: number; lockedColors?: AiLockedColor[] }) => Promise<boolean>;
        __paletteBrainLastResult?: unknown;
      };
      testWindow.__generateAiPalette = async (text, options) => {
        setPrompt(text);
        if (inputRef.current) inputRef.current.value = text;
        return await runGeneration(text, options);
      };
      return () => {
        delete testWindow.__generateAiPalette;
      };
    }
  }, [runGeneration]);

  return (
    <section
      className={`relative overflow-hidden rounded-2xl border border-purple-500/30 bg-gradient-to-b from-purple-950/30 via-zinc-950/80 to-zinc-950 p-4 sm:p-5 shadow-xl shadow-purple-950/20 backdrop-blur-sm space-y-4 ${className}`}
      aria-label={isRu ? 'AI генерация палитры' : 'AI palette generation'}
    >
      {/* Background subtle glow */}
      <div className="absolute -top-12 -right-12 w-32 h-32 bg-purple-500/10 rounded-full blur-2xl pointer-events-none" />

      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold uppercase tracking-wider bg-purple-500/15 text-purple-300 border border-purple-500/30 shadow-sm shadow-purple-900/30">
            <Sparkles className="w-3 h-3 text-purple-400 animate-pulse" />
            {isRu ? 'Локальный ИИ' : 'Local In-Browser AI'}
          </span>
        </div>
        <span className="text-[10px] font-mono text-gray-500 hidden sm:inline">
          {isRu ? 'ONNX WASM • Без внешних API' : 'ONNX WASM • 0 external APIs'}
        </span>
      </div>

      {/* Main unified Prompt Input Bar */}
      <div className="space-y-2">
        <label
          htmlFor="ai-palette-prompt"
          className="text-[11px] font-mono text-gray-400 block"
        >
          {isRu ? 'Опишите палитру, атмосферу или сцену:' : 'Describe a palette, scene, or mood:'}
        </label>
        
        <div className="relative rounded-xl border border-white/15 bg-zinc-900/90 hover:border-purple-500/40 focus-within:border-purple-400 focus-within:ring-2 focus-within:ring-purple-500/30 transition-all p-1.5 flex flex-col sm:flex-row items-stretch sm:items-center gap-2 shadow-inner">
          <div className="flex items-center flex-1 min-w-0 px-2 py-1">
            <input
              id="ai-palette-prompt"
              ref={inputRef}
              type="text"
              value={prompt}
              onChange={e => setPrompt(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder={isRu ? PLACEHOLDER_RU : PLACEHOLDER_EN}
              maxLength={4096}
              disabled={isGenerating}
              aria-busy={isGenerating}
              aria-label={isRu ? 'Текстовое описание палитры' : 'Palette description'}
              className="w-full bg-transparent border-none text-sm font-mono text-white placeholder-gray-500 focus:outline-none focus:ring-0"
            />
          </div>

          <button
            type="button"
            onClick={handleGenerate}
            disabled={!prompt.trim() || isGenerating}
            aria-disabled={!prompt.trim() || isGenerating}
            className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-xs font-mono font-bold text-white bg-gradient-to-r from-purple-600 via-purple-500 to-indigo-600 hover:from-purple-500 hover:via-purple-400 hover:to-indigo-500 active:scale-[0.98] shadow-md shadow-purple-900/40 hover:shadow-purple-700/50 transition-all disabled:opacity-40 disabled:pointer-events-none disabled:shadow-none shrink-0"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                <span>{isRu ? 'Генерация...' : 'Generating...'}</span>
              </>
            ) : (
              <>
                <Sparkles className="w-3.5 h-3.5 text-purple-200" />
                <span>{isRu ? 'Создать с AI' : 'Generate with AI'}</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Suggestion Chips */}
      <div className="flex items-center gap-1.5 flex-wrap">
        <span className="text-[10px] font-mono text-gray-500 mr-1">
          {isRu ? 'Идеи:' : 'Try:'}
        </span>
        {suggestions.map((s, idx) => (
          <button
            key={idx}
            type="button"
            onClick={() => handleChipClick(s)}
            className="px-2 py-0.5 rounded-md bg-zinc-900/80 hover:bg-purple-900/30 border border-white/5 hover:border-purple-500/30 text-[11px] font-mono text-gray-400 hover:text-purple-200 transition-colors"
          >
            {s}
          </button>
        ))}
      </div>

      {/* Error display */}
      {state === 'error' && error && (
        <div className="flex items-start gap-2 p-3 rounded-lg bg-red-950/40 border border-red-500/30">
          <AlertCircle className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" />
          <div className="flex-1 min-w-0">
            <p className="text-[11px] font-mono text-red-300 break-words">{error}</p>
            <button
              type="button"
              onClick={handleRetry}
              className="mt-1 text-[11px] font-mono text-red-400 hover:text-white underline"
            >
              {isRu ? 'Попробовать снова' : 'Retry'}
            </button>
          </div>
        </div>
      )}

      {lastResult?.fallback && (
        <div className="flex items-start gap-2 p-3 rounded-lg bg-amber-950/40 border border-amber-500/30">
          <AlertCircle className="w-4 h-4 text-amber-400 flex-shrink-0 mt-0.5" />
          <p className="text-[11px] font-mono text-amber-200">
            {isRu
              ? 'Модель сообщила о резервном режиме; этот результат показан явно.'
              : 'The model reported fallback mode; this result is shown explicitly.'}
          </p>
        </div>
      )}

      {/* Color count selector & local notice footer */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-3 border-t border-white/5">
        <div className="flex items-center gap-2">
          <span className="text-[11px] font-mono text-gray-400">
            {isRu ? 'Количество цветов:' : 'Colors:'}
          </span>
          <div className="flex gap-1" role="group" aria-label={isRu ? 'Количество цветов' : 'Color count'}>
            {COUNT_OPTIONS.map(n => (
              <button
                key={n}
                type="button"
                onClick={() => onCountChange(n)}
                aria-pressed={count === n}
                className={`w-7 h-7 rounded-md text-xs font-mono font-bold transition-all flex items-center justify-center ${
                  count === n
                    ? 'bg-purple-600 text-white border border-purple-400 shadow-sm shadow-purple-900/50'
                    : 'bg-zinc-900/80 text-gray-400 border border-white/10 hover:border-purple-500/40 hover:text-white'
                }`}
              >
                {n}
              </button>
            ))}
          </div>
        </div>

        <div className="text-right">
          <p className="text-[10px] font-mono text-gray-500">
            {isRu
              ? 'Нейросеть работает локально на вашем устройстве'
              : 'Runs locally on your device'}
          </p>
          {lastResult && (
            <p className="text-[9px] font-mono text-gray-600 mt-0.5">
              {lastResult.modelVersion}
              {typeof lastResult.inference?.totalMs === 'number'
                ? ` • ${Math.round(lastResult.inference.totalMs)} ms`
                : ''}
            </p>
          )}
        </div>
      </div>
    </section>
  );
});

AiPaletteInput.displayName = 'AiPaletteInput';
